name: update-lives-list

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.5  # 锁定 Python 版本

      - name: Install dependencies
        run: pip install -r requirements.txt  # 安装依赖项

      - name: Run iptv
        run: python ${{ github.workspace }}/iptv.py

      - name: 提交
        run: |
          git config --local user.email "253132876@qq.com"
          git config --local user.name "lizhun7740"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          git push -f
